#FROM openjdk:8-jdk-alpine
#FROM openjdk:11-jdk
FROM adoptopenjdk/openjdk11:latest
VOLUME /tmp
RUN apt-get update && apt-get -y install netcat && apt-get clean
ARG JAR_FILE
COPY ${JAR_FILE} user-dashboard.jar
COPY docker-entrypoint-user-dashboard.sh /
RUN chmod 755 docker-entrypoint-user-dashboard.sh
EXPOSE 20004
