#FROM openjdk:8-jdk-alpine
#FROM openjdk:11-jdk
FROM adoptopenjdk/openjdk11:latest
VOLUME /tmp
ARG JAR_FILE
COPY ${JAR_FILE} user-service.jar
EXPOSE 20003
ENTRYPOINT ["java", "-jar", "/user-service.jar"]
